#!/bin/bash

echo "=== Setting up MongoDB for CRM System ==="
echo ""
echo "MongoDB needs to be installed and running to use this application."
echo ""
echo "Installation instructions:"
echo ""
echo "For Ubuntu/Debian:"
echo "  sudo apt-get install -y mongodb"
echo "  sudo systemctl start mongodb"
echo ""
echo "For macOS:"
echo "  brew tap mongodb/brew"
echo "  brew install mongodb-community"
echo "  brew services start mongodb-community"
echo ""
echo "For Windows:"
echo "  Download from: https://www.mongodb.com/try/download/community"
echo ""
echo "After installation, MongoDB should be running on:"
echo "  mongodb://localhost:27017"
echo ""
echo "Then run: node index.js"
